version: '3.8'

services:
  vue-build-admin:
    image: node:lts
    container_name: vue-build-admin
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app # Монтируем текущую директорию в контейнер
    command: sh -c "npm install && npm run build-only" # Устанавливаем зависимости и запускаем сборку приложения
    restart: "no" # Не перезапускаем после завершения сборки
